### ISSUE TITLE
Add a confirmation DM when you have successfully spooked someone

### ISSUE THREAD

**Issue by andesyv** [lesesalen/lesebot#28]
Currently only the receiver of the spook gets any form of validation, and a reply in the channel would just add more spam, so the best solution would be to send a direct message to the person who requested the spook like a confirmation that it worked.

**Comment by andesyv** [comment]
Addressed in #29.

**Comment by sondr3** [comment]
Sånn FYI, du kan lukke issues direkte i commits [sånn her](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). Foretrekker det siden issues faktisk blir lukket når ting er merget og _faktisk_ løst :shipit:
