### ISSUE TITLE
Discord together activity

### ISSUE THREAD

**Issue by L0SER8228** [lesesalen/lesebot#58]
### What feature would you like to see?

Some discord together activity, such as watch together, doodlecrew, poker, fishington etc

### Additional information

Watch together activity alows to watch YouTube with friends together jn a Voice channel. Similarly others activity allows to play game with friends in a discord voice channel.

And I would like to add this features, if you found useful

**Comment by andesyv** [comment]
That sounds like a difficult but fun idea! As always, any contributions are very much welcome.

**Comment by L0SER8228** [comment]
No problem, I'll add this feature
